(function(){
  const key='deepnick-blog-data';
  const letters='ABCDEFGHIJKL'.split('');
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const read=()=>{try{return JSON.parse(localStorage.getItem(key)||'{}')}catch{return {}}};
  const save=d=>localStorage.setItem(key,JSON.stringify(d));
  let editingId=null,selected=[];
  const $=s=>document.querySelector(s);
  function getComp(id){return (read().competitions||[]).find(x=>x.id===id)}
  function cardFields(comp){const old=Object.fromEntries((comp?.problems||[]).map(p=>[p.letter,p]));return selected.map(l=>{const p=old[l]||{};return `<section class="problem-editor-card"><div class="problem-head"><span class="problem-letter">${l}</span><strong>第 ${l} 题</strong><span class="problem-tip">单独编辑</span></div><label>题目名称<input data-field="title" value="${esc(p.title||'')}" placeholder="例如：小红找数字"></label><label>知识点<input data-field="knowledge" value="${esc(p.knowledge||'')}" placeholder="字符串、DP、图论..."></label><label>题解正文<textarea data-field="body" rows="4" placeholder="写清思路、证明、复杂度和易错点...">${esc(p.body||'')}</textarea></label><label>代码<textarea data-field="code" rows="5" placeholder="void solve() { ... }">${esc(p.code||'')}</textarea></label></section>`}).join('')}
  function open(comp){editingId=comp?.id||null;selected=comp?.problems?.map(p=>p.letter)||['A'];const title=comp?'编辑比赛题解':'新建比赛题解';const art=$('#editorModal .editor-card');art.innerHTML=`<button class="modal-close" id="customEditorClose">×</button><span class="kicker">BLOG EDITOR</span><h2>${title}</h2><p class="editor-hint">请在 A-L 中任意勾选题号，可不连续选择；每个已选题号都会生成独立编辑卡片。</p><form id="customCompetitionForm"><div class="form-grid"><label>平台<select id="customPlatform"><option>牛客</option><option>AtCoder</option><option>Codeforces</option></select></label><label>比赛日期<input id="customDate" required placeholder="2024.08.18"></label></div><label>比赛名称<input id="customTitle" required placeholder="例如：牛客周赛 Round 157 题解"></label><label>比赛摘要<input id="customDesc" required placeholder="这场比赛的核心思路..."></label><div class="letter-picker"><div class="picker-label">选择题号 <span>可任意多选</span></div><div class="letter-options">${letters.map(l=>`<button type="button" class="letter-option ${selected.includes(l)?'selected':''}" data-letter="${l}">${l}</button>`).join('')}</div></div><div id="customProblemFields">${cardFields(comp)}</div><div class="editor-actions"><button type="button" class="ghost-btn" id="customEditorCancel">取消</button><button type="submit" class="pink-btn">保存比赛题解</button></div></form>`;$('#customPlatform').value=comp?.platform||'牛客';$('#customDate').value=comp?.date||'';$('#customTitle').value=comp?.title||'';$('#customDesc').value=comp?.desc||'';art.querySelectorAll('.letter-option').forEach(b=>b.onclick=()=>{const l=b.dataset.letter;if(selected.includes(l)){selected=selected.filter(x=>x!==l);b.classList.remove('selected')}else{selected.push(l);selected.sort();b.classList.add('selected')}$('#customProblemFields').innerHTML=cardFields(comp)});$('#customCompetitionForm').onsubmit=saveComp;$('#customEditorClose').onclick=close;$('#customEditorCancel').onclick=close;$('#editorModal').classList.add('open')}
  function saveComp(e){e.preventDefault();if(!selected.length){alert('请至少选择一道题');return}const d=read();d.competitions=d.competitions||[];const old=editingId?d.competitions.find(x=>x.id===editingId):null;const problems=[...document.querySelectorAll('#customProblemFields .problem-editor-card')].map(card=>({letter:card.querySelector('.problem-letter').textContent,title:card.querySelector('[data-field="title"]').value||`题目 ${card.querySelector('.problem-letter').textContent}`,knowledge:card.querySelector('[data-field="knowledge"]').value,body:card.querySelector('[data-field="body"]').value,code:card.querySelector('[data-field="code"]').value}));const c={id:editingId||'c'+Date.now(),platform:$('#customPlatform').value,date:$('#customDate').value,title:$('#customTitle').value,desc:$('#customDesc').value,problems,image:old?.image||''};if(old)Object.assign(old,c);else d.competitions.unshift(c);save(d);location.reload()}
  function close(){$('#editorModal')?.classList.remove('open')}
  function bind(){const n=$('#newSolutionBtn');if(n)n.onclick=()=>open(null);document.querySelectorAll('#solutionList .mini-edit').forEach(b=>{if(b.dataset.customBound)return;b.dataset.customBound='1';b.onclick=e=>{e.stopPropagation();const c=getComp(b.closest('.solution-item').dataset.id);open(c)}})}
  new MutationObserver(bind).observe(document.body,{childList:true,subtree:true});bind();
})();
